---
name: Encode-Arabic
version: 1.8
author:
  - 'Otakar Smrz <otakar smrz mff cuni cz>'
abstract: Encodings of Arabic
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  perl: 5.008
build_requires:
  Test::More: 0
provides:
  Encode::Arabic:
    file: lib/Encode/Arabic.pm
    version: 1.8
  Encode::Arabic::ArabTeX:
    file: lib/Encode/Arabic/ArabTeX.pm
    version: 7.17
  Encode::Arabic::ArabTeX::RE:
    file: lib/Encode/Arabic/ArabTeX/RE.pm
    version: 1.62
  Encode::Arabic::ArabTeX::Verbatim:
    file: lib/Encode/Arabic/ArabTeX/Verbatim.pm
    version: 7.17
  Encode::Arabic::ArabTeX::ZDMG:
    file: lib/Encode/Arabic/ArabTeX/ZDMG.pm
    version: 6.76
  Encode::Arabic::ArabTeX::ZDMG::RE:
    file: lib/Encode/Arabic/ArabTeX/ZDMG/RE.pm
    version: 1.43
  Encode::Arabic::Buckwalter:
    file: lib/Encode/Arabic/Buckwalter.pm
    version: 1.79
  Encode::Arabic::Parkinson:
    file: lib/Encode/Arabic/Parkinson.pm
    version: 1.79
  Encode::Mapper:
    file: lib/Encode/Mapper.pm
    version: 1.6
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
